# Generated by Django 4.2 on 2024-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_owner_post_owner'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='albums', to='posts.post'),
        ),
    ]
